name: Check Markdown
on:
  pull_request:
    paths:
      - "**.md"
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Santa"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
      - name: "Check for deadlinks"
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # ratchet:gaurav-nelson/github-action-markdown-link-check@1.0.15
      - name: "Check for trailing whitespace and newlines"
        run: "! git grep -EIn $'[ \t]+$' -- ':(exclude)*.patch'"
